// Table de correspondance IOC -> ISO2
const IOC_TO_ISO2 = {
  AFG: "AF",
  AHO: "CW",
  AIA: "AI",
  ALB: "AL",
  ALG: "DZ",
  ANA: "NL",
  AND: "AD",
  ANG: "AO",
  ANT: "AG",
  ARG: "AR",
  ARM: "AM",
  ART: "AG",
  ARU: "AW",
  ASA: "AS",
  AUS: "AU",
  AUT: "AT",
  AZE: "AZ",
  BAH: "BS",
  BAN: "BD",
  BAR: "BB",
  BDI: "BI",
  BEL: "BE",
  BEN: "BJ",
  BER: "BM",
  BHU: "BT",
  BIH: "BA",
  BIZ: "BZ",
  BLR: "BY",
  BOL: "BO",
  BOT: "BW",
  BRA: "BR",
  BRN: "BH",
  BUL: "BG",
  BUR: "BF",
  CAF: "CF",
  CAM: "KH",
  CAN: "CA",
  CAY: "KY",
  CGO: "CG",
  CHA: "TD",
  CHI: "CL",
  CHN: "CN",
  CIV: "CI",
  CMR: "CM",
  COD: "CD",
  COL: "CO",
  COM: "KM",
  CPV: "CV",
  CRC: "CR",
  CRO: "HR",
  CUB: "CU",
  CYP: "CY",
  CZE: "CZ",
  DEN: "DK",
  DJI: "DJ",
  DMA: "DM",
  DOM: "DO",
  ECU: "EC",
  EGY: "EG",
  ERI: "ER",
  ESA: "SV",
  ESP: "ES",
  EST: "EE",
  ETH: "ET",
  EUN: "RU",
  FIJ: "FJ",
  FIN: "FI",
  FRA: "FR",
  FRG: "DE",
  GAB: "GA",
  GAM: "GM",
  GBR: "GB",
  GDR: "DE",
  GEO: "GE",
  GER: "DE",
  GHA: "GH",
  GRE: "GR",
  GRN: "GD",
  GUA: "GT",
  GUI: "GN",
  GUY: "GY",
  HAI: "HT",
  HKG: "HK",
  HON: "HN",
  HUN: "HU",
  INA: "ID",
  IND: "IN",
  IRI: "IR",
  IRL: "IE",
  IRQ: "IQ",
  ISL: "IS",
  ISR: "IL",
  ISV: "VI",
  ITA: "IT",
  IVB: "VG",
  JAM: "JM",
  JOR: "JO",
  JPN: "JP",
  KAZ: "KZ",
  KEN: "KE",
  KGZ: "KG",
  KOR: "KR",
  KOS: "XK",
  KSA: "SA",
  KUW: "KW",
  LAT: "LV",
  LBA: "LY",
  LBN: "LB",
  LBR: "LR",
  LCA: "LC",
  LES: "LS",
  LIE: "LI",
  LTU: "LT",
  LUX: "LU",
  MAD: "MG",
  MAR: "MA",
  MAS: "MY",
  MAW: "MW",
  MDA: "MD",
  MEX: "MX",
  MGL: "MN",
  MLI: "ML",
  MLT: "MT",
  MNE: "ME",
  MNT: "ME",
  MON: "MC",
  MOZ: "MZ",
  MRI: "MU",
  MTN: "MR",
  MYA: "MM",
  NAM: "NA",
  NCA: "NI",
  NED: "NL",
  NEP: "NP",
  NGR: "NG",
  NIG: "NE",
  NOR: "NO",
  NZL: "NZ",
  OMA: "OM",
  PAK: "PK",
  PAN: "PA",
  PAR: "PY",
  PER: "PE",
  PHI: "PH",
  PLE: "PS",
  PNG: "PG",
  POL: "PL",
  POR: "PT",
  PRK: "KP",
  PUR: "PR",
  QAT: "QA",
  ROU: "RO",
  RSA: "ZA",
  RUS: "RU",
  RWA: "RW",
  SAM: "WS",
  SCG: "RS",
  SEN: "SN",
  SEY: "SC",
  SGP: "SG",
  SKN: "KN",
  SLE: "SL",
  SLO: "SI",
  SMR: "SM",
  SOM: "SO",
  SRB: "RS",
  SRI: "LK",
  SSD: "SS",
  STP: "ST",
  SUD: "SD",
  SUI: "CH",
  SUR: "SR",
  SVK: "SK",
  SWE: "SE",
  SWZ: "SZ",
  SYR: "SY",
  TAN: "TZ",
  TCH: "CZ",
  TGA: "TO",
  THA: "TH",
  TJK: "TJ",
  TKM: "TM",
  TKS: "TC",
  TOG: "TG",
  TPE: "TW",
  TTO: "TT",
  TUN: "TN",
  TUR: "TR",
  UAE: "AE",
  UGA: "UG",
  UKR: "UA",
  URU: "UY",
  URS: "RU",
  USA: "US",
  UZB: "UZ",
  VAN: "VU",
  VEN: "VE",
  VIE: "VN",
  VIN: "VC",
  YUG: "RS",
  ZAM: "ZM",
  ZIM: "ZW"
};

const unrecognizedCountryNames = {
  FRG: "West Germany",
  GDR: "East Germany",
  TCH: "Czechoslovakia",
  URS: "Soviet Union",
  YUG: "Yugoslavia",
  SCG: "Serbia and Montenegro",
  AHO: "Netherlands Antilles",
  ANA: "Netherlands Antilles"
};

const displayNamesCtor = Intl.DisplayNames;
const regionNames = displayNamesCtor ? new displayNamesCtor(["en"], { type: "region" }) : null;


const isoToFlag = (iso2) =>
  [...iso2.toUpperCase()].map((character) => String.fromCodePoint(127397 + character.charCodeAt(0))).join("");


export const getFlagFromNat = (natCode) => {
  const iso2 = IOC_TO_ISO2[String(natCode || "").trim().toUpperCase()];
  return iso2 ? isoToFlag(iso2) : " ";
};


export const getCountryNameFromNat = (natCode) => {
  const normalized = String(natCode || "").trim().toUpperCase();

  if (unrecognizedCountryNames[normalized]) {
    return unrecognizedCountryNames[normalized];
  }

  const iso2 = IOC_TO_ISO2[normalized];
  if (!iso2) {
    return normalized || "Unknown";
  }

  return (regionNames && regionNames.of(iso2)) || normalized;
};